### ISSUE TITLE
Please fix handling of FOSSHub

### ISSUE THREAD

**Issue by DavidSpivey** [eladkarako/Chrome-Extension-Real-URL#1]
For an example page that doesn't work with this extension, please see [MKVToolNix on FOSSHub](https://www.fosshub.com/MKVToolNix.html)

I know FOSSHub does some strange things, but when I follow one of the download links while this extension is installed, I am presented with a page saying the download link may have moved permanently.

I don't even mind if you make an exception rule for this site, just so it doesn't redirect me to a dead URL, causing me to need to disable the extension before downloading.

**Comment by eladkarako** [comment]
it does not looks like the extension has anything to do with it,
I've visited the page you've linked (above)- and the page seems to match zero rules from the heuristic query I use to discover elements on the page.
